defaults: &defaults
  simulation_program:
    call: "java -jar"
    path: <%= Rails.root.join('simulation.jar') %>
    options: "-i STDIN -o STDOUT -Xmx1024M"

  simulation_package_size: <%= File.stat(Rails.root.join('public', 'simulation.zip')).size %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults