defaults: &defaults
  simulation_program:
    call: "java -jar"
    path: <%= Rails.root.join('simulation.jar') %>
    options: "-i STDIN -o STDOUT -Xmx1024M"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults